[package]
name = "crazyflie-link"
version = "0.1.0"
authors = ["Arnaud Taffanel <arnaud@bitcraze.io>"]
edition = "2018"

[dependencies]
crazyradio = "0.1.5"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
log = "0.4"
rand = "0.8"
thiserror = "1"
url = "2.2"
hex = "0.4.3"

[dev-dependencies]
anyhow = "1"
structopt = "0.3"